apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: labs
  annotations:
    github.com/project-slug: baldwinsung/labs
    backstage.io/techdocs-ref: value

spec:
  type: other
  lifecycle: unknown
  owner: team-a
