---
- hosts: control_plane
  remote_user: ubuntu
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  remote_user: ubuntu
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['k8s01'].join_command }} >> node_joined.txt"
      args:
        chdir: /root
        creates: node_joined.txt
